"""anime and ratings tables

Revision ID: 1a8992efe615
Revises: 066925d2e669
Create Date: 2021-01-21 17:33:45.841056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8992efe615'
down_revision = '066925d2e669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anime_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_ratings_anime_id_animes'), 'animes', ['anime_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ratings_anime_id_animes'), type_='foreignkey')
        batch_op.drop_column('anime_id')

    # ### end Alembic commands ###
