"""update Animes table

Revision ID: 48cb99634644
Revises: 4ee16c5c0928
Create Date: 2021-01-19 13:22:27.249004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cb99634644'
down_revision = '4ee16c5c0928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ratings_anime_name_animes', type_='foreignkey')
        batch_op.drop_column('anime_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anime_name', sa.VARCHAR(length=256), nullable=True))
        batch_op.create_foreign_key('fk_ratings_anime_name_animes', 'animes', ['anime_name'], ['name'])

    # ### end Alembic commands ###
