"""animes table

Revision ID: a39059dc3570
Revises: 477fb181a611
Create Date: 2021-01-15 19:44:06.208931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39059dc3570'
down_revision = '477fb181a611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('episodes', sa.String(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('members', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animes_id'), 'animes', ['id'], unique=False)
    op.create_foreign_key(None, 'ratings', 'animes', ['anime_id'], ['id'])
    op.create_foreign_key(None, 'ratings', 'animes', ['anime_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_index(op.f('ix_animes_id'), table_name='animes')
    op.drop_table('animes')
    # ### end Alembic commands ###
